# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_MathFuncsDll', [dirname(__file__)])
        except ImportError:
            import _MathFuncsDll
            return _MathFuncsDll
        if fp is not None:
            try:
                _mod = imp.load_module('_MathFuncsDll', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _MathFuncsDll = swig_import_helper()
    del swig_import_helper
else:
    import _MathFuncsDll
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class LongInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LongInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LongInt, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _MathFuncsDll.new_LongInt()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _MathFuncsDll.delete_LongInt
    __del__ = lambda self: None

    def Read(self, flag, fname):
        return _MathFuncsDll.LongInt_Read(self, flag, fname)

    def __gt__(self, B):
        return _MathFuncsDll.LongInt___gt__(self, B)

    def __lt__(self, B):
        return _MathFuncsDll.LongInt___lt__(self, B)

    def __ge__(self, B):
        return _MathFuncsDll.LongInt___ge__(self, B)

    def __le__(self, B):
        return _MathFuncsDll.LongInt___le__(self, B)

    def __eq__(self, B):
        return _MathFuncsDll.LongInt___eq__(self, B)

    def __ne__(self, B):
        return _MathFuncsDll.LongInt___ne__(self, B)

    def __add__(self, a):
        return _MathFuncsDll.LongInt___add__(self, a)

    def __sub__(self, a):
        return _MathFuncsDll.LongInt___sub__(self, a)

    def __mul__(self, a):
        return _MathFuncsDll.LongInt___mul__(self, a)

    def __div__(self, a):
        return _MathFuncsDll.LongInt___div__(self, a)

    def __mod__(self, a):
        return _MathFuncsDll.LongInt___mod__(self, a)

    def Pow(self, a, b, mod):
        return _MathFuncsDll.LongInt_Pow(self, a, b, mod)

    def Print(self):
        return _MathFuncsDll.LongInt_Print(self)

    def CheckMinus(self):
        return _MathFuncsDll.LongInt_CheckMinus(self)

    def CheckSize(self):
        return _MathFuncsDll.LongInt_CheckSize(self)

    def WriteFile(self, flag, fname):
        return _MathFuncsDll.LongInt_WriteFile(self, flag, fname)
LongInt_swigregister = _MathFuncsDll.LongInt_swigregister
LongInt_swigregister(LongInt)

# This file is compatible with both classic and new-style classes.


